import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import LeftMenu from "@/components/LeftMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box sx={{ display: 'flex' }}>
          <LeftMenu />
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              p: 3,
              width: { sm: 'calc(100% - 240px)' },
              ml: { sm: '240px' },
              transition: 'margin-left 0.2s ease-in-out, width 0.2s ease-in-out',
              '&.collapsed': {
                width: { sm: 'calc(100% - 65px)' },
                ml: { sm: '65px' },
              },
            }}
            className="collapsed"
          >
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
